### ISSUE TITLE
Use ES aggregations on nested objects

### ISSUE THREAD

**Issue by vavarun** [nodkz/graphql-compose-elasticsearch#22]
As you can see below, my Sale schema field 'charges' is an Array of Objects.

```
const Sale = new mongoose.Schema(
  {
    company_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Company' },
    customer_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Customer' },
    charges: [{
      id: { type: String },
      amount: { type: Number, default: 0 },
      refunded: { type: Number, default: 0 },
    }]
})
```

I can't seem to use the sum aggregation in my saleEsConnection for 'Sale.charges.amount'. My current implementation:

```
const query =` gql
  {
    saleEsConnection(aggs:[
      {
        key: "total_sale_amount",
        value: {
          sum: {
            field: charges: {amount}
          }
        }
      }
    ])
    {
      aggregations
    }
  }
`;
```

**Comment by nodkz** [comment]
@vavarun debugging and helping with query construction can be done only with working elasticsearch server. Can you prepare public demo repo with schema (so i can clone repo and run it locally) and prepare public elasticsearch server with some demo data (to have the ability to connect ES server)?

Or you may use this scripts https://github.com/nodkz/graphql-compose-elasticsearch/tree/master/scripts/docker for creating docker container with ES and write some another script which will seed fresh docker container with data.

Anyway, without demo repo, we can not proceed.

PS. Now it's too late, will be on Monday.

**Comment by vavarun** [comment]
Hey @nodkz , for demo purposes I have created a repo with basic schemas for 3 Mongo DB collections and connected it with GraphiQl. The repo is connected to a cloud MongoDB and Elastic so should work straight away.

[https://github.com/vavarun/ESDemoWithMongoose](url)

**Comment by nodkz** [comment]
Great. I'll try to look it tomorrow and make PR to you repo with code fixes.

**Comment by nodkz** [comment]
Working query (fixed in https://github.com/nodkz/ESDemoWithMongoose/commit/78a99b4d793893233695824efb3fbf0fdc2abbb0):
```
{
  agentEsConnection {
    count
    edges {
      node {
        _id
        _source {
          name
        }
      }
    }
  }

  appointmentEsSearch {
    count
    hits {
      _id
      _source {
        agent_id
        customer_id
        time
        duration
        created_at
        updated_at
      }
    }
  }
}
```

**Comment by nodkz** [comment]
Aggregation query example in connection on `duration` and `updated_at` fields:
```
{
  appointmentEsConnection(
    sort: [created_at__asc, duration__asc],
    aggs: [
      { 
        key: "duration_stats",
        value: {        
          stats: {
            field: duration,
          },
        }
      },
      { 
        key: "duration_percentiles",
        value: {        
          percentiles: {
            field: duration,
          },
        }
      },
      {  
         key:"bucked_by_updated_at",
         value:{  
            date_range:{  
               field: updated_at,
               format:"dd-MM",
               ranges:[  
                  {  
                     from:"now-24h/h"
                  },
                  {  
                     from:"now-7d/d"
                  },
                  {  
                     from:"now-1M"
                  }
               ]
            }
         }
      },
    ]
  ) {
    aggregations
    count
    edges {
      node {
        _id
        _source {
          duration
          updated_at
        }
      }
    }
  }
}
```
